### ISSUE TITLE
[FEATURE] Ability to login using Databricks extension without configuration file

### ISSUE THREAD

**Issue by Gijsreyn** [databricks/databricks-vscode#1531]
**Describe the feature**

As a user, I would like to have the ability to log in without the need for the `databricks.yml` file. Currently, I have to fill in the required URL in the configuration file and then login.

The primary use case for this is that I'm building dynamic environments where the URL changes regularly. I don't want to check in the URL; instead, I prefer to leave it blank.

**Comment by ilia-db** [comment]
Hi, thanks for the feedback! The extension uses `databricks bundle *` CLI commands for many features (like syncing files to the workspace), but it should technically be possible to let users configure auth without modifying the `databricks.yml` file.

There's a possible improvement you can do that might help right now: the configuration file has a concept of targets, and you can define as many as you want, where each target can contain different workspace url. Sort of like this:

```
bundle:
  name: my_bundle

targets:
  one:
    workspace:
      host: https://one.databricks.com
  two:
    workspace:
      host: https://two.databricks.com
  three:
    workspace:
      host: https://three.databricks.com
  etc...
```

In the extension you can then switch targets by clicking on a cog wheel icon of the "Target" item in the configuration panel, or by executing a `Databricks: select a Databricks Asset Bundle target` command.

If you know a list of workspaces beforehand, you can define all of them in the `databricks.yml` and switch between them with just a couple of clicks.
