### ISSUE TITLE
[FEATURE] Add ability to override name_prefix on a resource-level

### ISSUE THREAD

**Issue by marcuseklund** [databricks/databricks-vscode#1548]
We are using name_prefixes in our deployment, which is very useful. Currently we create schemas using Terraform, and we would prefer to create them in the Asset Bundles.
It would be great to be able to override the name_prefix setting or ignore it on a resource-level. So when creating schemas, we would have better control over what the exact name should be.

Deploying this code in development target

```
resources:
  schemas:
    multi_market_optimization:
      name: "multi_market_optimization${var.schema_suffix}"
      catalog_name: ${var.power_catalog}
```

results in a schema called **dev_marcus_eklund_multi_market_optimization_marcus_eklund**

I would prefer to have it as **multi_market_optimization_marcus_eklund**. This would work if I could ignore/override the name_prefix setting when creating schemas.

The variable is defined as this in development
```
variables:
      schema_suffix: "_${workspace.current_user.short_name}"
```
