### ISSUE TITLE
[BUG] Extension databricks.databricks has provided an invalid tree item.

### ISSUE THREAD

**Issue by C0dingMast3r** [databricks/databricks-vscode#1634]
**Describe the bug**
When a complex variable is defined, it breaks the bundle variables visual

**To Reproduce**

1. Go to 'your databricks.yml file'
2. try to intsert the below variable:
```
variables:
  my_cluster:
    description: 'My cluster definition'
    type: complex
    default:
      spark_version: '13.2.x-scala2.11'
      node_type_id: 'Standard_DS3_v2'
      num_workers: 2
      spark_conf:
        spark.speculation: true
        spark.databricks.delta.retentionDurationCheck.enabled: false
```
3. See that Bundle Variables in the extension will break and you will get a popup saying:
`Extension databricks.databricks has provided an invalid tree item.`

**Screenshots**

![Image](https://github.com/user-attachments/assets/67a776bf-bc47-4308-bd72-da26d9124c4d)

![Image](https://github.com/user-attachments/assets/71be1e91-14fc-4b3b-bd48-864cbe1e1981)

**System information:**

1. Paste the output ot the `Help: About` command (CMD-Shift-P).
```
Version: 1.98.2 (user setup)
Commit: ddc367ed5c8936efe395cffeec279b04ffd7db78
Date: 2025-03-12T13:32:45.399Z
Electron: 34.2.0
ElectronBuildId: 11161602
Chromium: 132.0.6834.196
Node.js: 20.18.2
V8: 13.2.152.36-electron.0
OS: Windows_NT x64 10.0.22631
```

2. Databricks Extension Version: 2.9.1
**Databricks Extension Logs**
Please attach the [databricks extension logs](https://docs.databricks.com/en/dev-tools/vscode-ext/troubleshooting.html#send-usage-logs-to-databricks)
```
2025-03-30 15:15:58.542 [info] validate: Reading local bundle configuration for target user_dev...
2025-03-30 15:16:00.327 [info] validate: Finished reading local bundle configuration.
2025-03-30 15:16:00.340 [info] summarize: Refreshing bundle configuration for target user_dev...
2025-03-30 15:16:01.946 [info] summarize: Bundle configuration refreshed.
2025-03-30 15:16:09.616 [info] summarize: Refreshing bundle configuration for target user_dev...
2025-03-30 15:16:11.287 [info] summarize: Bundle configuration refreshed.
```

**Additional context**
Note: The issue is not in the logs as complex variables do work, its just that when used they break the visual component in BUNDLE Variables
